# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-10-14T14:39:05+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Extra, Field

from .model import HistoryModel


class HistoryResponse(BaseModel):
    class Config:
        extra = Extra.forbid

    result: List[HistoryModel]
    cursor: Optional[str] = None
    total: float
