# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2022-10-14T14:39:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra

from .model import AbiItem, Block, InternalTransaction, Log, Transaction
